@url = http://localhost:8000/api/v1

### GET PLAN TYPES
GET {{url}}/plan-types HTTP/1.1
Content-Type: application/json
Authorization: Bearer your_token_here


### SHOW PLAN TYPE
GET {{url}}/plan-types/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer your_token_here


### GET PLAN TYPES WITH PLAN
GET {{url}}/plan-types/2/plans HTTP/1.1
Content-Type: application/json
Authorization: Bearer your_token_here


### GET PLANS
GET {{url}}/plans HTTP/1.1
Content-Type: application/json
Authorization: Bearer your_token_here

### GET PLANS SPECIFIC
GET {{url}}/plans/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer your_token_here

### GET PLANS WITH INVENTORY
GET {{url}}/plans/1/inventory HTTP/1.1
Content-Type: application/json
Authorization: Bearer your_token_here
