import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Operator/OperatorCard.tsx
import React from 'react';
import { Link } from '@tanstack/react-router';
import { OptimizedImage } from '../Image/Image';
export const OperatorCard = ({ operator }) => {
    const hasData = operator.has_data_plans;
    const hasTalktime = operator.has_talktime;
    const totalPlans = operator.plan_types?.reduce((sum, pt) => sum + (pt.available_coupons_count || 0), 0) || 0;
    return (_jsx(Link, { to: "/operator/$id", params: { id: operator.id.toString() }, className: "group relative block", preload: "intent", children: _jsxs("div", { className: "relative overflow-hidden rounded-3xl bg-base-200/50 backdrop-blur-sm border border-base-300/30 shadow-lg hover:shadow-2xl transition-all duration-500 hover:scale-[1.02] hover:-translate-y-2", children: [_jsx("div", { className: "h-2 bg-gradient-to-r from-primary via-secondary to-accent" }), _jsxs("div", { className: "p-8 text-center space-y-6", children: [_jsxs("div", { className: "relative mx-auto w-32 h-32", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-primary/20 to-secondary/20 rounded-full blur-xl scale-110 group-hover:scale-125 transition-transform duration-700" }), _jsx("div", { className: "relative z-10 w-full h-full rounded-full overflow-hidden ring-4 ring-white/50 shadow-2xl", children: _jsx(OptimizedImage, { src: operator.logo || '/placeholder-operator.svg', alt: operator.name, className: "w-full h-full object-contain p-6 bg-white", loading: "lazy" }) })] }), _jsx("h3", { className: "text-2xl font-bold tracking-tight", children: operator.name }), _jsxs("div", { className: "flex flex-wrap gap-2 justify-center", children: [hasData && (_jsx("span", { className: "badge badge-lg badge-primary shadow-md", children: "Data Plans" })), hasTalktime && (_jsx("span", { className: "badge badge-lg badge-success shadow-md", children: "Talktime" })), totalPlans > 20 && (_jsx("span", { className: "badge badge-lg badge-accent shadow-md", children: "Hot" }))] }), _jsxs("div", { className: "text-sm text-base-content/60 space-y-1", children: [_jsxs("p", { className: "font-semibold text-lg text-primary", children: [totalPlans, " plans available"] }), _jsx("p", { className: "text-xs", children: operator.country.name })] })] }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-transparent via-white/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none" })] }) }));
};
