/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as SettingRouteImport } from './routes/setting';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as PublicRegisterRouteImport } from './routes/_public/register';
import { Route as PublicLoginRouteImport } from './routes/_public/login';
import { Route as AuthenticatedSuccessRouteImport } from './routes/_authenticated/success';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedOperatorIndexRouteImport } from './routes/_authenticated/operator/index';
import { Route as AuthenticatedCheckoutIndexRouteImport } from './routes/_authenticated/checkout/index';
import { Route as AuthenticatedProductIdRouteImport } from './routes/_authenticated/product/$id';
import { Route as AuthenticatedOperatorIdRouteRouteImport } from './routes/_authenticated/operator/$id/route';
import { Route as AuthenticatedOperatorIdPlanRouteRouteImport } from './routes/_authenticated/operator/$id/plan/route';
import { Route as AuthenticatedOperatorIdPlanIdRouteImport } from './routes/_authenticated/operator/$id/plan/$id';
const SettingRoute = SettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const PublicRoute = PublicRouteImport.update({
    id: '/_public',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedRoute = AuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoute,
});
const PublicRegisterRoute = PublicRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => PublicRoute,
});
const PublicLoginRoute = PublicLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => PublicRoute,
});
const AuthenticatedSuccessRoute = AuthenticatedSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedOperatorIndexRoute = AuthenticatedOperatorIndexRouteImport.update({
    id: '/operator/',
    path: '/operator/',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedCheckoutIndexRoute = AuthenticatedCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedProductIdRoute = AuthenticatedProductIdRouteImport.update({
    id: '/product/$id',
    path: '/product/$id',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedOperatorIdRouteRoute = AuthenticatedOperatorIdRouteRouteImport.update({
    id: '/operator/$id',
    path: '/operator/$id',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedOperatorIdPlanRouteRoute = AuthenticatedOperatorIdPlanRouteRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthenticatedOperatorIdRouteRoute,
});
const AuthenticatedOperatorIdPlanIdRoute = AuthenticatedOperatorIdPlanIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOperatorIdPlanRouteRoute,
});
const AuthenticatedOperatorIdPlanRouteRouteChildren = {
    AuthenticatedOperatorIdPlanIdRoute: AuthenticatedOperatorIdPlanIdRoute,
};
const AuthenticatedOperatorIdPlanRouteRouteWithChildren = AuthenticatedOperatorIdPlanRouteRoute._addFileChildren(AuthenticatedOperatorIdPlanRouteRouteChildren);
const AuthenticatedOperatorIdRouteRouteChildren = {
    AuthenticatedOperatorIdPlanRouteRoute: AuthenticatedOperatorIdPlanRouteRouteWithChildren,
};
const AuthenticatedOperatorIdRouteRouteWithChildren = AuthenticatedOperatorIdRouteRoute._addFileChildren(AuthenticatedOperatorIdRouteRouteChildren);
const AuthenticatedRouteChildren = {
    AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
    AuthenticatedSuccessRoute: AuthenticatedSuccessRoute,
    AuthenticatedIndexRoute: AuthenticatedIndexRoute,
    AuthenticatedOperatorIdRouteRoute: AuthenticatedOperatorIdRouteRouteWithChildren,
    AuthenticatedProductIdRoute: AuthenticatedProductIdRoute,
    AuthenticatedCheckoutIndexRoute: AuthenticatedCheckoutIndexRoute,
    AuthenticatedOperatorIndexRoute: AuthenticatedOperatorIndexRoute,
};
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren);
const PublicRouteChildren = {
    PublicLoginRoute: PublicLoginRoute,
    PublicRegisterRoute: PublicRegisterRoute,
};
const PublicRouteWithChildren = PublicRoute._addFileChildren(PublicRouteChildren);
const rootRouteChildren = {
    AuthenticatedRoute: AuthenticatedRouteWithChildren,
    PublicRoute: PublicRouteWithChildren,
    ProfileRoute: ProfileRoute,
    SettingRoute: SettingRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
